In [1]:
import re
import numpy as np
import pickle
import nltk
from nltk.corpus import stopwords
from sklearn.datasets import load_files

In [ ]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


In [3]:
reviews = load_files('txt_sentoken/')

In [4]:
X,y = reviews.data,reviews.target

In [5]:
#Storing the pickle file
with open('X.pickle','wb') as f:
    pickle.dump(X,f)

In [6]:
with open('y.pickle','wb') as f:
    pickle.dump(y,f)

In [7]:
# Unpickling the file
with open('X.pickle','rb') as f:
    X = pickle.load(f)

In [8]:
with open('y.pickle','rb') as f:
    y = pickle.load(f)

In [9]:
print(len(X))

2000


In [10]:
#Creating the corpus

corpus = []
for i in range(0, len(X)):
    review = re.sub(r'\W',' ',str(X[i]))
    review = review.lower()
    review = re.sub(r'\s+[a-z]\s+',' ',review)
    review = re.sub(r'^[a-z]\s+',' ',review)
    review = re.sub(r'\s+',' ',review)
    corpus.append(review)
    
    

In [11]:
len(corpus)

2000

In [12]:
corpus[200]

' having not seen who framed roger rabbit in over 10 years and not remembering much besides that liked it then decided to rent it recently nwatching it was struck by just how brilliant film it is naside from the fact that it a milestone in animation in movies it the first film to combine real actors and cartoon characters have them interact and make it convincingly real and great entertainment it also quite an effective comedy mystery nwhile the plot may be somewhat familiar the characters are original especially baby herman and watching them together is lot of fun nthe story begins in hollywood in 1947 ncartoon star roger rabbit is blowing takes and having trouble keeping his mind on work so hard boiled private detective eddie valiant bob hoskins is called in by studio head k nmaroon alan tilvern to try to help get roger mind back on work nmaroon thinks that roger wife jessica possible unfaithfulness to him might be the cause of distraction and tells eddie to get some photos of her in

# BOW model

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=10000,min_df=4,max_df=0.6,
                            stop_words=stopwords.words('english'))


In [14]:
X = vectorizer.fit_transform(corpus).toarray()

In [15]:
len(X)

2000

In [16]:
X.shape

(2000, 10000)

In [17]:
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]]


# TFIDF Model from CounterVectorizer

In [18]:
from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer()

In [19]:
X = transformer.fit_transform(X).toarray()

In [20]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.08911014, 0.        , ..., 0.        , 0.        ,
        0.        ]])

# TFidf Vectorizer

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=10000,min_df=4,max_df=0.6,
                            stop_words=stopwords.words('english'))

X = vectorizer.fit_transform(corpus).toarray()

In [22]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.08911014, 0.        , ..., 0.        , 0.        ,
        0.        ]])

# Word2Vectore

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.3, random_state=0)

In [36]:
X_train.shape, y_train.shape

((1400, 10000), (1400,))

In [118]:
X_test.shape,y_test.shape

((600, 10000), (600,))

# Model Analysis

In [97]:
from sklearn.linear_model import LogisticRegression

In [98]:
classifier =LogisticRegression()

In [119]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [120]:
prediction = classifier.predict(X_test)

In [121]:
from sklearn.metrics import confusion_matrix,accuracy_score
import seaborn

In [122]:
ConMatrix = confusion_matrix(y_test,prediction)

In [123]:
ConMatrix

array([[241,  62],
       [ 37, 260]], dtype=int64)

In [124]:
score = accuracy_score(y_test,prediction)

In [125]:
score

0.835

# Naiv bayes 

In [106]:
from sklearn.naive_bayes import MultinomialNB

In [107]:
nb = MultinomialNB()

In [126]:
nb.fit(X_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [127]:
pred = nb.predict(X_test);

In [128]:
score = accuracy_score(y_test,pred)
score

0.8183333333333334

In [129]:
confusion_matrix(y_test,pred)

array([[249,  54],
       [ 55, 242]], dtype=int64)

# Save the model

In [112]:
with open('classifier.pickle','wb') as f:
    pickle.dump(classifier,f)
    

In [113]:
with open('tfidfmodel.pickle','wb') as f:
    pickle.dump(vectorizer,f)

# Word2Vector

In [ ]:
from gensim.models import Word2Vec

In [ ]:
X = Word2Vec(corpus, min_count=2,size=5000)