In [1]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore', category=DeprecationWarning)

In [2]:
train=pd.read_csv('train.csv')
test=pd.read_csv('test.csv')

In [4]:
trdf=pd.read_csv('en_train.csv')
valdf=pd.read_csv('en_val.csv')
tstdf=pd.read_csv('en_test.csv')

In [5]:
y_train=trdf.Survived
trdf.drop('Survived',axis=1,inplace=True)
y_test=valdf.Survived
valdf.drop('Survived',axis=1,inplace=True)
X_train=trdf
X_test=valdf
Xtest=tstdf


AttributeError: 'DataFrame' object has no attribute 'Survived'

In [41]:
X_train.head()

Age  Alone  Cabin  Embarked  FamilySize  Fare  LargeFamily  Parch  Pclass  \
0  1.0      0      0         0           2     0            0      0       3   
1  2.0      0      1         1           2     3            0      0       1   
2  1.0      1      0         0           1     1            0      0       3   
3  2.0      0      1         0           2     3            0      0       1   
4  2.0      1      0         0           1     1            0      0       3   

   Sex  SibSp  SmallFamily  Title  person  Sib+Parch  Age+SibSp  Age+Parch  \
0    0      1            1      0       0          1        2.0        1.0   
1    1      1            1      2       1          1        3.0        2.0   
2    1      0            0      1       1          0        1.0        1.0   
3    1      1            1      2       1          1        3.0        2.0   
4    0      0            0      0       0          0        2.0        2.0   

   Age*Fare  Pclass+SibSp  
0       0.0             3  
1       6.0             1  
2       1.0             0  
3       6.0             1  
4       2.0             0

In [87]:
X_train = pd.read_csv('en_train1.csv')
X_test = pd.read_csv('en_val1.csv')
Xtest= pd.read_csv('en_test1.csv')

In [43]:
X_train_std.head()

AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [42]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#standardizing after splitting
sc = StandardScaler().fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#standardizing before splitting
#data_std = StandardScaler().fit_transform(data)
#X_train, X_test, y_train, y_test = train_test_split(data_std, target)

# Modelling 

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score,cross_val_predict
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix




In [20]:
#X_train,X_test,y_train,y_test = train_test_split(train,test,test_size=.5)

In [29]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    '''
    print the accuracy score, classification report and confusion matrix of classifier
    '''
    if train:
        '''
        training performance
        '''
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train.ravel(), cv=4, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        
    elif train==False:
        '''
        test performance
        '''
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test))))    
        

# Model 1: Decision Tree

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [11]:
dt_clf = DecisionTreeClassifier()
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [12]:
print_score(dt_clf, X_train, y_train, X_test, y_test, train=True)
print_score(dt_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.9034

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.88      0.97      0.92       271
        1.0       0.95      0.80      0.87       174

avg / total       0.91      0.90      0.90       445


Confusion Matrix: 
 [[263   8]
 [ 35 139]]

Average Accuracy: 	 0.8539
Accuracy SD: 		 0.0463
Test Result:

accuracy score: 0.7668

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.78      0.87      0.82       278
        1.0       0.74      0.59      0.66       168

avg / total       0.76      0.77      0.76       446


Confusion Matrix: 
 [[243  35]
 [ 69  99]]



# model 3:AdaBoost

In [44]:
from sklearn.ensemble import AdaBoostClassifier


In [45]:
from sklearn.ensemble import BaggingClassifier

In [46]:
class_weight = {0:0.834, 1:0.166}

In [47]:
ada_clf = AdaBoostClassifier(base_estimator=svc_clf, n_estimators=100,
                         learning_rate=0.5,random_state=42)
ada_clf.fit(X_train_std,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
          base_estimator=SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=4, gamma='auto', kernel='poly',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
          learning_rate=0.5, n_estimators=100, random_state=42)

In [49]:
print_score(ada_clf, X_train_std, y_train, X_test_std, y_test, train=True)
print_score(ada_clf, X_train_std, y_train, X_test_std, y_test, train=False)

Train Result:

accuracy score: 0.6090

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.61      1.00      0.76       271
        1.0       0.00      0.00      0.00       174

avg / total       0.37      0.61      0.46       445


Confusion Matrix: 
 [[271   0]
 [174   0]]

Average Accuracy: 	 0.6090
Accuracy SD: 		 0.0022
Test Result:

accuracy score: 0.6233

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.62      1.00      0.77       278
        1.0       0.00      0.00      0.00       168

avg / total       0.39      0.62      0.48       446


Confusion Matrix: 
 [[278   0]
 [168   0]]



# Model 4: Logistic 

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
logcv = LogisticRegression()
logcv.fit(X_train_std,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [52]:
print_score(logcv, X_train_std, y_train, X_test_std, y_test, train=True)
print_score(logcv, X_train_std, y_train, X_test_std, y_test, train=False)

Train Result:

accuracy score: 0.8270

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.84      0.88      0.86       271
        1.0       0.80      0.75      0.77       174

avg / total       0.83      0.83      0.83       445


Confusion Matrix: 
 [[238  33]
 [ 44 130]]

Average Accuracy: 	 0.8203
Accuracy SD: 		 0.0156
Test Result:

accuracy score: 0.8274

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.84      0.90      0.87       278
        1.0       0.81      0.71      0.76       168

avg / total       0.83      0.83      0.82       446


Confusion Matrix: 
 [[250  28]
 [ 49 119]]



In [20]:
print_score(logcv, X_train, y_train, X_test, y_test, train=True)
print_score(logcv, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.9034

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.93      0.91      0.92       271
        1.0       0.86      0.90      0.88       174

avg / total       0.90      0.90      0.90       445


Confusion Matrix: 
 [[246  25]
 [ 18 156]]

Average Accuracy: 	 0.9011
Accuracy SD: 		 0.0391
Test Result:

accuracy score: 0.7758

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.82      0.81      0.82       278
        1.0       0.70      0.71      0.71       168

avg / total       0.78      0.78      0.78       446


Confusion Matrix: 
 [[226  52]
 [ 48 120]]



# Model 5: Support Vector

In [53]:
from sklearn.svm import SVC

In [54]:
svc_clf = SVC(probability=True,kernel = 'poly',degree=4,C=1)
svc_clf.fit(X_train_std,y_train)


SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=4, gamma='auto', kernel='poly',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [56]:
print_score(svc_clf, X_train_std, y_train, X_test_std, y_test, train=True)
print_score(svc_clf, X_train_std, y_train, X_test_std, y_test, train=False)

Train Result:

accuracy score: 0.8000

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.76      0.97      0.86       271
        1.0       0.93      0.53      0.67       174

avg / total       0.83      0.80      0.78       445


Confusion Matrix: 
 [[264   7]
 [ 82  92]]

Average Accuracy: 	 0.7461
Accuracy SD: 		 0.0033
Test Result:

accuracy score: 0.7623

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.74      0.95      0.83       278
        1.0       0.85      0.45      0.59       168

avg / total       0.78      0.76      0.74       446


Confusion Matrix: 
 [[265  13]
 [ 93  75]]



In [24]:
print_score(svc_clf, X_train, y_train, X_test, y_test, train=True)
print_score(svc_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.8697

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.86      0.94      0.90       271
        1.0       0.89      0.76      0.82       174

avg / total       0.87      0.87      0.87       445


Confusion Matrix: 
 [[254  17]
 [ 41 133]]

Average Accuracy: 	 0.7978
Accuracy SD: 		 0.0131
Test Result:

accuracy score: 0.8072

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.81      0.91      0.85       278
        1.0       0.81      0.64      0.71       168

avg / total       0.81      0.81      0.80       446


Confusion Matrix: 
 [[253  25]
 [ 61 107]]



# Model 6: Gradient Boosting

In [57]:
from sklearn.ensemble import GradientBoostingClassifier
gb_clf= GradientBoostingClassifier(learning_rate=0.01,random_state=1)
gb_clf.fit(X_train_std, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.01, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=1, subsample=1.0, verbose=0,
              warm_start=False)

In [58]:
print_score(gb_clf, X_train_std, y_train, X_test_std, y_test, train=True)
print_score(gb_clf, X_train_std, y_train, X_test_std, y_test, train=False)

Train Result:

accuracy score: 0.8337

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.85      0.88      0.87       271
        1.0       0.80      0.76      0.78       174

avg / total       0.83      0.83      0.83       445


Confusion Matrix: 
 [[238  33]
 [ 41 133]]

Average Accuracy: 	 0.8158
Accuracy SD: 		 0.0123
Test Result:

accuracy score: 0.8184

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.82      0.91      0.86       278
        1.0       0.81      0.67      0.74       168

avg / total       0.82      0.82      0.81       446


Confusion Matrix: 
 [[252  26]
 [ 55 113]]



In [108]:
print_score(gb_clf, X_train, y_train, X_test, y_test, train=True)
print_score(gb_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.9034

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.88      0.97      0.92       271
        1.0       0.95      0.80      0.87       174

avg / total       0.91      0.90      0.90       445


Confusion Matrix: 
 [[263   8]
 [ 35 139]]

Average Accuracy: 	 0.8698
Accuracy SD: 		 0.0234
Test Result:

accuracy score: 0.7713

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.78      0.88      0.83       278
        1.0       0.75      0.59      0.66       168

avg / total       0.77      0.77      0.76       446


Confusion Matrix: 
 [[245  33]
 [ 69  99]]



# Extra Tree

In [26]:
from sklearn.ensemble import ExtraTreesClassifier

In [27]:
et_clf = ExtraTreesClassifier()

In [28]:
et_clf.fit(X_train,y_train)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [29]:
print_score(et_clf, X_train, y_train, X_test, y_test, train=True)
print_score(et_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.9034

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.88      0.97      0.92       271
        1.0       0.95      0.80      0.87       174

avg / total       0.91      0.90      0.90       445


Confusion Matrix: 
 [[263   8]
 [ 35 139]]

Average Accuracy: 	 0.8539
Accuracy SD: 		 0.0463
Test Result:

accuracy score: 0.7803

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.79      0.87      0.83       278
        1.0       0.75      0.62      0.68       168

avg / total       0.78      0.78      0.78       446


Confusion Matrix: 
 [[243  35]
 [ 63 105]]



# Knn

In [59]:
from sklearn.neighbors import KNeighborsClassifier

In [60]:
knn_clf=KNeighborsClassifier()

In [61]:
knn_clf.fit(X_train_std,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [62]:
print_score(knn_clf, X_train_std, y_train, X_test_std, y_test, train=True)
print_score(knn_clf, X_train_std, y_train, X_test_std, y_test, train=False)

Train Result:

accuracy score: 0.8427

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.85      0.90      0.87       271
        1.0       0.82      0.76      0.79       174

avg / total       0.84      0.84      0.84       445


Confusion Matrix: 
 [[243  28]
 [ 42 132]]

Average Accuracy: 	 0.8002
Accuracy SD: 		 0.0367
Test Result:

accuracy score: 0.8229

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.82      0.91      0.86       278
        1.0       0.82      0.68      0.74       168

avg / total       0.82      0.82      0.82       446


Confusion Matrix: 
 [[253  25]
 [ 54 114]]



In [33]:
print_score(knn_clf, X_train, y_train, X_test, y_test, train=True)
print_score(knn_clf, X_train, y_train, X_test, y_test, train=False)

Train Result:

accuracy score: 0.9034

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.91      0.93      0.92       271
        1.0       0.89      0.86      0.87       174

avg / total       0.90      0.90      0.90       445


Confusion Matrix: 
 [[252  19]
 [ 24 150]]

Average Accuracy: 	 0.8809
Accuracy SD: 		 0.0428
Test Result:

accuracy score: 0.7780

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.81      0.85      0.83       278
        1.0       0.73      0.66      0.69       168

avg / total       0.78      0.78      0.78       446


Confusion Matrix: 
 [[236  42]
 [ 57 111]]



In [34]:
Xtest.isnull().sum()

dt_clf     0
et_clf     0
ada_clf    0
svc_clf    0
logcv      0
gb_clf     0
knn_clf    0
dtype: int64

# ensemble of ensembling

In [35]:
en_train = pd.DataFrame()
en_val = pd.DataFrame()
en_test = pd.DataFrame()

In [36]:
en_train['dt_clf'] = pd.DataFrame(dt_clf.predict_proba(X_train))[1]
en_train['et_clf'] =  pd.DataFrame(et_clf.predict_proba(X_train))[1]
en_train['ada_clf'] =  pd.DataFrame(ada_clf.predict_proba(X_train))[1]
en_train['svc_clf'] =  pd.DataFrame(svc_clf.predict_proba(X_train))[1]
en_train['logcv'] =  pd.DataFrame(logcv.predict_proba(X_train))[1]
en_train['gb_clf'] =  pd.DataFrame(gb_clf.predict_proba(X_train))[1]
#en_train['vote_clf'] =  pd.DataFrame(vote_clf.predict(X_train))
en_train['knn_clf'] =  pd.DataFrame(knn_clf.predict_proba(X_train))[1]
#en_train = pd.concat([en_train, pd.DataFrame(y_train).reset_index(drop=True)], axis=1)

In [37]:
en_val['dt_clf'] = pd.DataFrame(dt_clf.predict_proba(X_test))[1]
en_val['et_clf'] =  pd.DataFrame(et_clf.predict_proba(X_test))[1]
en_val['ada_clf'] =  pd.DataFrame(ada_clf.predict_proba(X_test))[1]
en_val['svc_clf'] =  pd.DataFrame(svc_clf.predict_proba(X_test))[1]
en_val['logcv'] =  pd.DataFrame(logcv.predict_proba(X_test))[1]
en_val['gb_clf'] =  pd.DataFrame(gb_clf.predict_proba(X_test))[1]
en_val['knn_clf'] =  pd.DataFrame(knn_clf.predict_proba(X_test))[1]
#en_val['vote_clf'] =  pd.DataFrame(vote_clf.predict(X_test))

In [38]:
#Xtest['Title'].isnull().sum()

In [39]:
en_test['dt_clf'] = pd.DataFrame(dt_clf.predict_proba(Xtest))[1]
en_test['et_clf'] =  pd.DataFrame(et_clf.predict_proba(Xtest))[1]
en_test['ada_clf'] =  pd.DataFrame(ada_clf.predict_proba(Xtest))[1]
en_test['svc_clf'] =  pd.DataFrame(svc_clf.predict_proba(Xtest))[1]
en_test['logcv'] =  pd.DataFrame(logcv.predict_proba(Xtest))[1]
en_test['gb_clf'] =  pd.DataFrame(gb_clf.predict_proba(Xtest))[1]
en_test['knn_clf'] =  pd.DataFrame(knn_clf.predict_proba(Xtest))[1]
#en_test['vote_clf'] =  pd.DataFrame(vote_clf.predict(Xtest))

In [40]:
en_train.head()

dt_clf  et_clf   ada_clf   svc_clf     logcv    gb_clf  knn_clf
0    0.25    0.25  0.494603  0.076034  0.202920  0.300035      0.2
1    1.00    1.00  0.598564  0.941952  0.966185  0.776737      1.0
2    0.60    0.60  0.501909  0.845425  0.720467  0.529065      0.6
3    1.00    1.00  0.598564  0.941953  0.966185  0.776737      1.0
4    0.50    0.50  0.500184  0.476032  0.501642  0.461019      0.4

In [41]:
print(en_train.shape,en_val.shape,en_test.shape)

(445, 7) (446, 7) (418, 7)


In [42]:
en_train.to_csv('en_train4.csv',index=False)

In [43]:
en_val.to_csv('en_val4.csv',index=False)

In [44]:
en_test.to_csv('en_test4.csv',index=False)

# Extra Tree

In [90]:
en_train_df = pd.read_csv('en_train4.csv')
en_val_df = pd.read_csv('en_val4.csv')
en_test_df = pd.read_csv('en_test4.csv')

In [46]:
en_val_df.head()

dt_clf  et_clf   ada_clf   svc_clf     logcv    gb_clf  knn_clf
0     1.0    1.00  0.598564  0.936719  0.963056  0.776737      1.0
1     1.0    1.00  0.598564  0.941884  0.966179  0.776737      1.0
2     0.5    0.50  0.500184  0.458382  0.583107  0.461019      0.4
3     0.4    0.51  0.500629  0.478501  0.639064  0.460574      0.4
4     0.0    0.00  0.396420  0.061330  0.046006  0.143893      0.0

In [26]:
from sklearn.ensemble import ExtraTreesClassifier,GradientBoostingClassifier,RandomForestClassifier,BaggingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB

C:\Users\Faysal\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [48]:

rf=RandomForestClassifier()
nb=GaussianNB()

In [49]:
rf.fit(en_val_df,y_test)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [50]:
#print_score(nb, en_train_df, y_train, en_val_df, y_test, train=True)
print_score(rf, en_train_df, y_train, en_val_df, y_test, train=False)

Test Result:

accuracy score: 0.9081

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.89      0.97      0.93       278
        1.0       0.94      0.80      0.87       168

avg / total       0.91      0.91      0.91       446


Confusion Matrix: 
 [[270   8]
 [ 33 135]]



# Bagging

In [27]:
bag_clf = BaggingClassifier(base_estimator=svc_clf, n_estimators=100,
                            max_samples=1.0, max_features=1.0, bootstrap=True,
                            bootstrap_features=False, n_jobs=-1,
                            random_state=42)

In [63]:
bag_clf.fit(X_train_std, y_train)

BaggingClassifier(base_estimator=SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=4, gamma='auto', kernel='poly',
  max_iter=-1, probability=True, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=100, n_jobs=-1, oob_score=False,
         random_state=42, verbose=0, warm_start=False)

In [64]:
print_score(bag_clf, X_train_std, y_train, X_test_std, y_test, train=True)
print_score(bag_clf, X_train_std, y_train, X_test_std, y_test, train=False)

Train Result:

accuracy score: 0.7978

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.76      0.97      0.85       271
        1.0       0.93      0.52      0.67       174

avg / total       0.83      0.80      0.78       445


Confusion Matrix: 
 [[264   7]
 [ 83  91]]

Average Accuracy: 	 0.7415
Accuracy SD: 		 0.0052
Test Result:

accuracy score: 0.7691

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.75      0.95      0.84       278
        1.0       0.86      0.46      0.60       168

avg / total       0.79      0.77      0.75       446


Confusion Matrix: 
 [[265  13]
 [ 90  78]]



In [111]:
print_score(bag_clf, en_train_df, y_train, en_val_df, y_test, train=True)
print_score(bag_clf, en_train_df, y_train, en_val_df, y_test, train=False)

Train Result:

accuracy score: 0.8989

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.87      0.99      0.92       271
        1.0       0.97      0.76      0.86       174

avg / total       0.91      0.90      0.90       445


Confusion Matrix: 
 [[267   4]
 [ 41 133]]

Average Accuracy: 	 0.8990
Accuracy SD: 		 0.0155
Test Result:

accuracy score: 0.7825

Classification Report: 
              precision    recall  f1-score   support

        0.0       0.78      0.90      0.84       278
        1.0       0.78      0.58      0.67       168

avg / total       0.78      0.78      0.77       446


Confusion Matrix: 
 [[251  27]
 [ 70  98]]



In [54]:
temp=pd.read_csv('en_test2.csv')

In [55]:
temp.head()

dt_clf   et_clf   ada_clf   svc_clf     logcv    gb_clf  knn_clf
0  0.000000  0.00000  0.394286  0.038198  0.043854  0.143893      0.0
1  0.857143  0.35493  0.500406  0.500000  0.339450  0.368117      0.6
2  0.000000  0.00000  0.394742  0.031130  0.054416  0.143893      0.0
3  0.161290  0.16129  0.491742  0.082186  0.130193  0.238273      0.4
4  0.000000  0.00000  0.394762  0.069804  0.050102  0.143893      0.0

# Prediction

In [91]:
en_test_df.head()

dt_clf   et_clf   ada_clf   svc_clf     logcv    gb_clf  knn_clf
0  0.00000  0.00000  0.396420  0.061257  0.045993  0.143893      0.0
1  0.40000  0.51000  0.500629  0.471417  0.638222  0.460574      0.4
2  0.00000  0.00000  0.396420  0.061224  0.045997  0.143893      0.0
3  0.16129  0.16129  0.491789  0.072235  0.114378  0.238273      0.2
4  0.00000  0.00000  0.396420  0.060298  0.046192  0.143893      0.0

In [83]:
output = svc_clf.predict(en_test_df).astype(int)
df_output = pd.DataFrame()
aux = pd.read_csv('test.csv')
df_output['PassengerId'] = aux['PassengerId']
df_output['Survived'] = output
df_output[['PassengerId','Survived']].to_csv('svc2_submission.csv', index=False)

NameError: name 'en_test_df' is not defined

In [58]:
print("Done")

Done
